/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as RequestRouteImport } from './routes/request'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPaperImageFileIdRouteImport } from './routes/api/public/paper-image.$fileId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaperImageFileIdRoute =
  ApiPublicPaperImageFileIdRouteImport.update({
    id: '/api/public/paper-image/$fileId',
    path: '/api/public/paper-image/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/papers': typeof PapersRoute
  '/request': typeof RequestRoute
  '/tips': typeof TipsRoute
  '/upload': typeof UploadRoute
  '/api/public/paper-image/$fileId': typeof ApiPublicPaperImageFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/papers': typeof PapersRoute
  '/request': typeof RequestRoute
  '/tips': typeof TipsRoute
  '/upload': typeof UploadRoute
  '/api/public/paper-image/$fileId': typeof ApiPublicPaperImageFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/papers': typeof PapersRoute
  '/request': typeof RequestRoute
  '/tips': typeof TipsRoute
  '/upload': typeof UploadRoute
  '/api/public/paper-image/$fileId': typeof ApiPublicPaperImageFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/papers'
    | '/request'
    | '/tips'
    | '/upload'
    | '/api/public/paper-image/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/papers'
    | '/request'
    | '/tips'
    | '/upload'
    | '/api/public/paper-image/$fileId'
  id:
    | '__root__'
    | '/'
    | '/papers'
    | '/request'
    | '/tips'
    | '/upload'
    | '/api/public/paper-image/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PapersRoute: typeof PapersRoute
  RequestRoute: typeof RequestRoute
  TipsRoute: typeof TipsRoute
  UploadRoute: typeof UploadRoute
  ApiPublicPaperImageFileIdRoute: typeof ApiPublicPaperImageFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paper-image/$fileId': {
      id: '/api/public/paper-image/$fileId'
      path: '/api/public/paper-image/$fileId'
      fullPath: '/api/public/paper-image/$fileId'
      preLoaderRoute: typeof ApiPublicPaperImageFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PapersRoute: PapersRoute,
  RequestRoute: RequestRoute,
  TipsRoute: TipsRoute,
  UploadRoute: UploadRoute,
  ApiPublicPaperImageFileIdRoute: ApiPublicPaperImageFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
